FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    apt-utils \
    bash \
    curl \
    git \
    gnupg \
    less \
    lsof \
    net-tools \
    unzip \
    wget \
    xz-utils \
    openjdk-8-jre \
    file \
    zip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -' \
    && sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list' \
    && apt-get update && apt-get install dart \
    && wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.6-stable.tar.xz
ENV PATH $PATH:/usr/lib/dart/bin
ENV PATH $PATH:/usr/lib/flutter/bin
RUN tar xf /flutter_linux_1.22.6-stable.tar.xz -C /usr/lib/ \
    && flutter precache