version: '3'
services:
    app:
        container_name: flutter_app
        build: .
        volumes: 
            - ..:/code
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /root/.Xauthority:/root/.Xauthority
        tty: true
        network_mode: "host"